### PR TITLE
Release as a universal wheel

### PR DESCRIPTION
**Pull request by adamchainz**
By releasing as a [Python wheel](http://pythonwheels.com/) as well as a source distribution, you can speed up end user’s installs. After merging this command, to release you just need to run `python setup.py clean sdist bdist_wheel upload`.

### CODE REVIEW

**Comment by miracle2k** [comment]
I ran `python setup.py clean  bdist_wheel upload` which I think will have added the wheel file for the current release.

Thanks.

**Comment by adamchainz** [comment]
But you didn't merge my PR?

**Comment by adamchainz** [comment]
(btw yes it's there at https://pypi.python.org/pypi/glob2 )

**Comment by miracle2k** [comment]
I just missed the push :)

**Pull request closed without merging**
