### PR TITLE
Optionally return also hidden files and folders

### PR DESCRIPTION
**Pull request by scoobadog**

### CODE REVIEW

**Comment by scoobadog** [comment]
I noticed after I created the pull request that there was an open issue #9 about this functionality. This implementation is a bit different from what was discussed but I hope that it will suffice.

**Comment by miracle2k** [comment]
It looks good, however, it does break the tests.

You can run those with "py.test tests.py".

**Comment by scoobadog** [comment]
Hi, I have now redesigned the functionality so that the tests won't break.

**Comment by miracle2k** [comment]
Thanks.

**Pull request merged**
